select: 
  - platform: template
    id: handles_animation_select
    name: "Handles Animation:"
    optimistic: true
    restore_value: true
    # make sure the ordering is the same as in the C++ enum!
    options:
      - Swipe
      - Distance
      - Random
    initial_option: Random
    set_action:
      lambda:  id(animator).pick(static_cast<animator24::handles_animation::Enum>(id(handles_animation_select).index_of(x).value_or(0)));
esphome:
  on_boot:
    then:
      - lambda: id(animator).pick(static_cast<animator24::handles_animation::Enum>(id(handles_animation_select).active_index().value_or(0)));
switch:
  - platform: template
    entity_category: 'animator'
    name: "Handles Animation: Swipe"
    restore_state: true
    lambda: return id(animator).state(animator24::handles_animation::Swipe);
    turn_on_action:
      - lambda: id(animator).turn_on(animator24::handles_animation::Swipe);
    turn_off_action:
      - lambda: id(animator).turn_off(animator24::handles_animation::Swipe);
  - platform: template
    entity_category: 'animator'
    name: "Handles Animation: Distance"
    restore_state: true
    lambda: return id(animator).state(animator24::handles_animation::Distance);
    turn_on_action:
      - lambda: id(animator).turn_on(animator24::handles_animation::Distance);
    turn_off_action:
      - lambda: id(animator).turn_off(animator24::handles_animation::Distance);

