esphome:
  name: ${node_name}
  platform: ESP8266
  board: nodemcuv2
  esp8266_restore_from_flash: true

i2c:  

pcf8574: # depends on i2c
  - id: 'pcf8574_hub'
    address: 0x38
    pcf8575: false

time:
  - platform: homeassistant
    id: current_time   

# home assistant support
#api: # depends on wifi
#  password: !secret api_password 