esphome:
  name: ${node_name}
#  platformio_options:
#    board_build.f_cpu: 80000000L
  libraries:
    - ESP8266TimerInterrupt
#    - "EspSoftwareSerial"

esp8266:      
  board: nodemcuv2
  framework:
    version: recommended
  restore_from_flash: true

i2c:  

pcf8574: # depends on i2c
  - id: 'pcf8574_hub'
    address: 0x38
    pcf8575: false

time: # depends on api 
  - platform: homeassistant
    id: current_time   
